### ISSUE TITLE
Reverse order of Community Spaces postings

### ISSUE THREAD

**Issue by adanbar** [Simon-Initiative/oli-torus#4072] opened 2023-08-03 02:00 UTC
New posts are made at the top of the screen but they then appear at the bottom of existing posts. This means that people will reference posts "below" when writing, which then are "above" once posted.  Confusing. Would be better to follow Google Docs comment model where posts are entered in the same place where they appear.

See below for an example of this confusion appearing in early "real world" testing.

![image](https://github.com/Simon-Initiative/oli-torus/assets/141290940/552ab821-fa2e-4749-a95c-78ca7a9421b5)

**Comment by darrensiegel** [comment] 2023-08-03 12:10
Closing as a duplicate of https://eliterate.atlassian.net/browse/MER-2316

**Closed by darrensiegel** 2023-08-03 12:10 UTC
