### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by reburchill** [Simon-Initiative/oli-torus#4040] opened 2023-07-27 18:50 UTC
Unexpected Beh.

If the user drags the initiator (input) to the wrong area (gets incorrect answer), and drags back to the start area but places it into a different area the feedback breaks and does not mark it correct/incorrect.  

This should be correct

![![Broken Drag   Drop](https://github.com/Simon-Initiative/oli-torus/assets/140545778/72e7ad6d-917a-44ff-b6c4-ca5dfbd3c196)

![image](https://github.com/Simon-Initiative/oli-torus/assets/140545778/dac20396-f07d-4981-92fd-a55844cbbe3e)

**Environment (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by andersweinstein** [comment] 2023-08-01 20:56
Is this preview mode? There are some odd limits in preview mode. It might be appropriate to freeze an answer once entered in preview mode. The multi-input activity does this and drag-and-drop can be thought of as an interface to a multi-input.

**Comment by tanvidomadia** [comment] 2023-08-01 22:24
No, not in preview mode but happens in [student view](https://proton.oli.cmu.edu/sections/mockup__os/page/modern_windows_os). 

Steps to reproduce the error: 

1. Place the initiator to the wrong area to get an incorrect answer.
2. Place the initiator back to the start area but in a different placeholder (for e.g. The initiators are initially placed as initiator 1, initiator 2, initiator 3 and if you move initiator 1 from their original place to where initiator 3 is). 
3. Place the initiator back into the correct area 
4. See error (feedback is not presented for the initiator)

For example, see image below with no feedback: 

![Screenshot 2023-08-01 at 14-40-44 Modern Windows OS](https://github.com/Simon-Initiative/oli-torus/assets/20156664/afb0b3f7-9fc4-41e1-b4f1-e3a51c254c8a)

**Comment by andersweinstein** [comment] 2023-08-01 23:24
This looks like similar issue to one addressed by https://github.com/Simon-Initiative/oli-torus/pull/3636 -- same error message in console window.
Perhaps this is a case that fix missed.

**Comment by bitbldr** [comment] 2023-08-29 17:21
fixed v0.24.3

**Closed by bitbldr** 2023-08-29 17:21 UTC
Labels: Priority 2: High, Area: Delivery, Jira, Hotfix
