### ISSUE TITLE
Grace period option not presented to student

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3430] opened 2023-04-25 15:41 UTC
I created a product with a $25 fee and a 1-day grace period. It's not an option for my student account.
https://proton.oli.cmu.edu/authoring/products/hal_test_01

![Screenshot 2023-04-25 at 11 40 41 AM](https://user-images.githubusercontent.com/24977416/234330264-9f4cb64a-2a7d-42de-829c-f24c32b6bf98.png)
![Screenshot 2023-04-25 at 11 40 48 AM](https://user-images.githubusercontent.com/24977416/234330296-d4f873a4-1b7f-4418-88e6-878874f7eb35.png)
![Screenshot 2023-04-25 at 11 40 59 AM](https://user-images.githubusercontent.com/24977416/234330373-43f7af7d-1dab-4550-b655-36c6ea29cd8a.png)

**Comment by darrensiegel** [comment] 2023-04-25 16:00
Torus does not present an explicit option to the student to "use the grace period".  Rather, if a grace period is enabled and the student hasn't paid, they have access.   I believe what you are seeing in your course section is that the grace period has expired (you have it relative to section start)

Students will see a banner indicating that they are accessing within the grace period:

![Screenshot 2023-04-25 at 11 57 22 AM](https://user-images.githubusercontent.com/7431756/234335423-2869b73a-c5b0-4c78-8dac-713eca9a0974.png)

**Comment by halturner** [comment] 2023-04-25 16:49
Possible cause may be inability to assign Start and End dates to LTI sections, rendering the grace period "based on start date" non-functional.

**Comment by halturner** [comment] 2023-04-25 17:41
After changing the product's grace period setting to "based on student registration date" the grace period works.
This setting is only used for courses with rolling enrollments, where it doesn't make sense to use the Start Date as the grace period's grounding point. Most courses are delivered per-semester and using this setting results in dozens or more students having very different grace period expirations. That's a management problem for the instructor; instead all grace periods should end at the same time, so the "based on start date" setting needs to be used.
![Screenshot 2023-04-25 at 1 39 00 PM](https://user-images.githubusercontent.com/24977416/234358103-31fc4f1d-acb7-4017-916e-08e3d186ad6f.png)

**Comment by eliknebel** [comment] 2023-04-25 18:51
https://eliterate.atlassian.net/browse/MER-1924

**Comment by darrensiegel** [comment] 2023-05-04 02:26
Duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3475

**Closed by darrensiegel** 2023-05-04 02:26 UTC
Labels: Priority_1:_Critical
