### ISSUE TITLE
"This project has no active course sections" despite LTI-connected section

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3465] opened 2023-05-02 22:04 UTC
[This project has no active course sections.](https://proton.oli.cmu.edu/authoring/project/hals_sandbox_111522/publish)
![Screenshot 2023-05-03 at 9 38 09 AM](https://user-images.githubusercontent.com/24977416/235932581-4f21b461-e52c-40e6-ab17-d8682453f1d2.png)

[Here is the active course section.](https://proton.oli.cmu.edu/sections/torus_test_abgps)
<img width="1608" alt="Screenshot 2023-05-03 at 9 36 48 AM" src="https://user-images.githubusercontent.com/24977416/235932259-7a3e987d-60af-4ed2-b3f5-d10d986cba6e.png">

**Comment by darrensiegel** [comment] 2023-05-04 02:27
Duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3475

**Closed by darrensiegel** 2023-05-04 02:27 UTC
