### ISSUE TITLE
Delete attached objective dialog is inconsistent  

### ISSUE THREAD

**Issue by rgachuhi** [Simon-Initiative/oli-torus#367] opened 2020-07-09 16:38 UTC
Try deleting an attache objective, dialog listing where it’s attached is displayed, close that dialog and try deleting another attached objective, the dialog is never displayed

**Comment by darrensiegel** [comment] 2020-07-24 11:33
Closing this, as I cannot reproduce it.

**Closed by darrensiegel** 2020-07-24 11:33 UTC
Labels: bug
