### ISSUE TITLE
Cannot attain 100% course progress

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3784] opened 2023-06-27 18:19 UTC
Several of us have tried to attain 100% in this course, and can only attain 75%:
https://proton.oli.cmu.edu/sections/join/tfmno

1. Enroll as a non-guest student.
2. Answer each question on the four pages
3. Visit the Home page and note your completion percentage is only 75%

**Comment by eliknebel** [comment] 2023-07-11 18:31
Could be related to revisiting a completed page resetting progress for that page

**Comment by darrensiegel** [comment] 2023-07-11 19:34
Closing, unless reproducible in v24.  This is almost certainly because the project/product customization resulted in an unreachable page being included in the section, hence the inability to attain 100% progress. Unreachable page culling was added into v24 section creation and remix.

Moreover, in some cases, even with unreachable page culling, it will be impossible to achieve 100% progress.  Many adaptive lessons are specifically designed in a way that not every screen (aka "activity") is able to visited.

**Closed by darrensiegel** 2023-07-11 19:34 UTC
Labels: Bug, Priority 1: Critical, Fix v24, Jira
