### ISSUE TITLE
Canceling a credit card payment leads to unexpected results

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3467] opened 2023-05-03 14:19 UTC
Description and steps to reproduce:

1. Access LTI course as student and click Pay Now.
2. Note your Dark Mode selection; if in Light Mode, take note as it may be relevant later (but not the cause of the problem).
3. Choose first option, "Pay now"
4. Click Pay Now button
5. Note new tab opens for Cashnet interface. Click CANCEL and confirm.
6. Student lands on empty My Courses page stating "You are not enrolled in any courses."
7. Note Dark Mode is now engaged, when it was not previously. 
8. Click the OLI Torus logo in the top left to find yourself on the Home page of your LTI-connected course, which is now open in two tabs.

https://user-images.githubusercontent.com/24977416/235944423-966ecefa-b442-4c09-bd68-0aed6584e03e.mov

**Comment by darrensiegel** [comment] 2023-05-09 22:19
Duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3462

**Closed by darrensiegel** 2023-05-09 22:19 UTC
Labels: Priority_1:_Critical
