### ISSUE TITLE
Text Wrap in inline input question

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3765] opened 2023-06-25 23:20 UTC
This lbd in torus - text wrap doesn't seem to  be working properly.
![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/d74df030-fc66-4cc6-a682-416c756799d7)

https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_24/page/5s48r_accuracy_and_precision_8uy7g

It should look like this: 

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/c61f0f6d-4b3f-481b-a2bf-16f22308a680)

**Comment by darrensiegel** [comment] 2023-06-26 12:17
Duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3749

**Closed by darrensiegel** 2023-06-26 12:17 UTC
