### ISSUE TITLE
Navigation back to Manage Course page from Assessment Settings page

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3719] opened 2023-06-16 15:59 UTC
There is no navigation / breadcrumb trail back from the Assessment Settings to the Manage Course page (tested on Stellarator)

**Comment by normanbier** [comment] 2023-06-17 17:40
Duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3714

**Closed** 2023-06-20 18:45 UTC
