### ISSUE TITLE
"Complete" button on quizzes unnecessary and can cause confusion 

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3449] opened 2023-05-02 14:18 UTC
Why is this button here? It opens the overview in this tab - again confusing. https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_extra_practice_properties_of_m_jmftt

![image](https://user-images.githubusercontent.com/36045601/235693754-58ddfe4c-a5ec-47f3-a1f0-ae5ad4da8668.png)

Same button on the review page. These buttons don't exist in Legacy and I don't think they should in Torus. Or they should do something different and not open the overview page. 

![image](https://user-images.githubusercontent.com/36045601/235694139-044002e0-8849-4a9f-9c71-cb62d55ab701.png)

**Comment by darrensiegel** [comment] 2023-05-04 02:15
Duplicate of #3448

**Closed by darrensiegel** 2023-05-04 02:15 UTC
