### ISSUE TITLE
Warning Message on Quiz Submit

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3456] opened 2023-05-02 14:48 UTC
In legacy, if you try to submit without filling in some of the answers you get a warning message. Not the case in Torus. 

![image](https://user-images.githubusercontent.com/36045601/235702110-b793aa6e-4224-4578-8d22-0252366e7557.png)

**Comment by darrensiegel** [comment] 2023-05-04 02:20
Duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3403

**Closed by darrensiegel** 2023-05-04 02:20 UTC
