### ISSUE TITLE
Single input not visible on authoring menu

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3144] opened 2022-11-28 17:11 UTC
**Describe the bug**
Single input question type is cut off when adding new content

**Screenshots**
![image](https://user-images.githubusercontent.com/32859465/204339185-3f884ba6-9db5-455a-bc0b-928ba37851d6.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 0.21.5 (3BEB47B) 09/01/2022

**Additional context**
Multiple new items were recently added to this menu, so perhaps the box padding needs to be adjusted?

**Comment by darrensiegel** [comment] 2022-11-30 02:29
This is a duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3005

**Closed by darrensiegel** 2022-11-30 02:29 UTC
