### ISSUE TITLE
(migration bug) Feedback on second to last question on page is not showing up

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4390] opened 2023-11-02 22:50 UTC
**Describe the bug**
Feedback on second to last question on page is not showing up. Something to do with the correct answer not being selected according to Anders in the migration meeting. 
[SVN
](https://svn.oli.cmu.edu/svn/community/stem/fast_track/branches/v_1_1-echo/content/Unit_workplace_comm/m3_writing_skills/x-oli-workbook_page/developanddemonstrateawritingprocess1a.xml)[Echo](https://echo.oli.cmu.edu/#fast_track-1.1/developanddemonstrateawritingprocess1a?organization=fast_track-1.1_default)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=8c1e03220a0001dc5fdd5e5feb830b4a)
[Tokamak](https://tokamak.oli.cmu.edu/sections/stem_foundations_102023/page/urlgr_the_writing_process_organizing_q50d6)

**Environment (please complete the following information):**
 - Version: 26

**Additional context**
High Priority course for India project

**Comment by andersweinstein** [comment] 2023-11-03 01:52
The problem is that no correct choice -- one with non-zero score -- is specified for this question and torus requires one. Notice legacy behavior is odd: all choices get correct feedback (green with checkmark). Possible this was desired?

Migration tool is supposed to detect and "fix" this condition by arbitrarily picking the first choice to be correct.  Not clear why that is not happening, but it can be fixed in xml source by making one answer correct, which looks like it should in fact be the first choice in this case. 

https://echo.oli.cmu.edu/#fast_track-1.1/Writing_Process_DIGT_2?organization=fast_track-1.1_default

**Comment by bitbldr** [comment] 2023-11-28 19:55
Will be fixed in XML

**Closed by bitbldr** 2023-11-28 19:55 UTC
