### ISSUE TITLE
Viewing Unit/Module numbers in Course content outline

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#4253] opened 2023-09-27 21:00 UTC
**Is your feature request related to a problem? Please describe.**
The course content outline does not show any unit/ module/ page numbers. It is valuable for instructors to have the unit/module numbers so if the instructor wants them to go through Unit 5, Module 2, they can easily navigate to the same. 

<img width="339" alt="Screenshot 2023-09-27 at 1 56 05 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/20156664/93aa35b8-80b1-4c8e-8946-fe98ad31ef08">

**Describe the solution you'd like**
Having precise module numbers or unit numbers in the outline is helpful. 

**Describe alternatives you've considered**
- Course outline page as an add-on along with the narrow pane on the left.

**Comment by darrensiegel** [comment] 2023-09-28 13:42
Duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3617

**Closed by darrensiegel** 2023-09-28 13:42 UTC
