### ISSUE TITLE
Student completion percentages exceeding 100%

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4114] opened 2023-08-16 14:28 UTC
**Describe the bug**
Student completion percentages are exceeding 100%

**To Reproduce**
[See this REAL Chem content report.
](https://proton.oli.cmu.edu/sections/real_chemistry_i__07212023/instructor_dashboard/reports)
<head>

**Expected behavior**
Anything between 0% and 100%

**Screenshots**
<img width="1424" alt="Screenshot 2023-08-16 at 10 26 35 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/24fd992a-0879-4a1d-8005-c6859f9b057a">

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 
 - Version: 116.0.5845.96 (Official Build) (arm64)

**Additional context**
This is a recent reversion. It was less than 100% as recently as a day or two ago.

**Comment by darrensiegel** [comment] 2023-08-16 20:39
This problem only manifests in course sections that are marked as `:archived` or `:deleted`.

Root cause is the `Oli.Delivery.Sections.count_enrollments(section_slug)` function, for some reason, only considers `:active` sections.

**Comment by bitbldr** [comment] 2023-08-29 18:25
https://eliterate.atlassian.net/browse/MER-2508

**Closed** 2023-08-30 01:10 UTC
Labels: Priority 3: Normal
