### ISSUE TITLE
In LTI, cannot apply schedule because Start/End dates are required

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3442] opened 2023-04-25 19:33 UTC
As an LTI instructor, clicking Manage Section > (Curriculum) Scheduling leads to an error notifying the instructor about the need for Start/End dates:
<img width="1608" alt="Screenshot 2023-04-25 at 3 32 21 PM" src="https://user-images.githubusercontent.com/24977416/234383323-5fefa543-0a14-4f2a-82fc-228447d9aa61.png">

Following the provided link takes the instructor to a page where the Start/End dates cannot be applied.

https://user-images.githubusercontent.com/24977416/234383651-116fd818-2b5b-4430-b273-23c5c099f607.mov

**Comment by darrensiegel** [comment] 2023-05-04 02:23
Duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3475

**Closed by darrensiegel** 2023-05-04 02:23 UTC
