### ISSUE TITLE
(Migration Parity) Pullout style is missing on migrated course

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4385] opened 2023-11-02 22:15 UTC
**Describe the bug**
Pullout style is missing on migrated course. This is utilized heavily in this course. 

[SVN](https://svn.oli.cmu.edu/svn/community/stem/fast_track/branches/v_1_1-echo/content/Unit_workplace_comm/m1_app_read_strat/x-oli-workbook_page/Identifythemainideaandsupportingdetailsofatext_1.xml)
[Echo](https://echo.oli.cmu.edu/#fast_track-1.1/Identifythemainideaandsupportingdetailsofatext_1?organization=fast_track-1.1_default)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=8c1e028f0a0001dc302e7babefbe7c27)
<img width="862" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/d8003071-4e38-4498-a36b-304a8c31afdd">

[Tokamak](https://tokamak.oli.cmu.edu/sections/stem_foundations_102023/page/urlgr_apply_reading_strategies_to_im_tznpt)
<img width="714" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/b8f967c8-b936-405f-94f8-67e4d4eab71f">

**Environment (please complete the following information):**
 - Version: 26

**Additional context**
High Priority course for India project

**Comment by bitbldr** [comment] 2023-11-07 19:34
Related to https://github.com/Simon-Initiative/oli-torus/issues/3659

**Comment by bitbldr** [comment] 2023-11-07 19:39
Duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3659. Recommendation is to bring to migration meeting to get it into a work queue

**Closed by bitbldr** 2023-11-07 19:39 UTC
