### ISSUE TITLE
Migration: Extra space being added after first character in many elements (title, paragraphs, multiple choice, etc)

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3692] opened 2023-06-12 20:29 UTC
**Describe the bug**
Extra space inserted after the T in Test.

**Screenshots**
Page: Test 1 Review
<img width="884" alt="Screen Shot 2023-06-12 at 4 28 39 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/d31e6571-3320-4358-b6f3-7b87198494c7">
<img width="877" alt="Screen Shot 2023-06-12 at 4 28 47 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/c73ee6e2-4408-432c-9941-7e708ea18ccd">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_stats_main_campus_spring_2/page/589t9_test_1_review_bkuhw)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d7660a0001dc169923c44be78d10)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:** None

**Comment by eliknebel** [comment] 2023-06-12 22:51
https://eliterate.atlassian.net/browse/MER-2157

**Comment by cjlim1092** [comment] 2023-06-13 17:24
SVN: https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/x-oli-workbook_page/d1fcb0d3ae824751baed41d8e229e5fa.xml

**Comment by cjlim1092** [comment] 2023-06-13 17:26
Related to [#3607](https://github.com/Simon-Initiative/oli-torus/issues/3607) - can merge these issues

**Comment by eliknebel** [comment] 2023-06-13 18:49
Duplicate of  https://github.com/Simon-Initiative/oli-torus/issues/3607

**Closed by eliknebel** 2023-06-13 18:49 UTC
