### ISSUE TITLE
[Stellarator]: Instructor Dashboard: Learning objectives view not loading in Reports tab

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#3827] opened 2023-07-05 18:27 UTC
**Description**
In the Instructor dashboard, the learning objective view is not loading in the Reports tab. 

**To Reproduce**
1. Go to any course on stellarator.oli.cmu.edu as an instructor. 
2. Click on Reports tab
3. Scroll down and click on Learning objectives sub-tab
4. The screen loads the same page/ sub-tab that you are on and doesn't go to the learning objectives sub-tab. 

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
If the instructor is on any other sub-tab, and clicks on the learning objectives sub-tab the same thing happens and it remains on that sub-tab and doesn't load the learning objectives view.

**Comment by darrensiegel** [comment] 2023-07-09 21:47
Dupe of #3817

**Closed by darrensiegel** 2023-07-09 21:47 UTC
