### ISSUE TITLE
(Migration) Images are loaded without line breaks

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3436] opened 2023-04-25 18:00 UTC
**Describe the bug**
Occasionally in a migrated course there is no line break/ images are in-line with their surrounding text. Images should always appear in image fields. 

**To Reproduce**
[Tokamak](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_linear_relationships_4_of_8_01nwk)
[legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d6da0a0001dc39638a51166c6eeb) 
[echo](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.8/linear4?organization=georgia_state_stats_master_liu-5.8_x2z4ga6r)
[xml](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_8-echo/content/_u2_summarizing_data/_m2_examining_relationships/x-oli-workbook_page/linear4.xml)

**Screenshots**
Note where it says the top in this screenshot
![image](https://user-images.githubusercontent.com/32859465/234362750-15f7274a-92cc-4918-b472-569f6af325b2.png)

Legacy:
<img width="932" alt="Screenshot 2023-04-25 at 2 08 33 PM" src="https://user-images.githubusercontent.com/6248894/234364471-2653d903-c8b0-476e-b14b-254a9c3e92be.png">

**Environment (please complete the following information):**
 - Version: 23

**Comment by eliknebel** [comment] 2023-04-25 18:18
https://eliterate.atlassian.net/browse/MER-1919

**Comment by andersweinstein** [comment] 2023-05-06 14:08
Likely duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3451: the digest tool is converting certain block images to inline images.

**Closed** 2024-09-06 13:42 UTC
Labels: Priority 2: High, Migration
