### ISSUE TITLE
Navigation boxes at bottom of page have text layout problems

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3732] opened 2023-06-20 15:46 UTC
**Describe the bug**
The "Next" and "Previous" navigation boxes at the bottom of the page often contain text that overlaps the boxes and other elements on the page. This happens with longer page titles. Example screenshots included below.

Example page: https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_18/page/vuswd_units_of_solution_concentratio_qd5nl

![Screenshot from 2023-06-19 20-03-30](https://github.com/Simon-Initiative/oli-torus/assets/2669407/e4853117-deca-41cb-9a90-7e1262d20b58)

![Screenshot from 2023-06-19 20-04-35](https://github.com/Simon-Initiative/oli-torus/assets/2669407/df031352-de5a-4a76-bd49-b88b0ee619ca)

**Comment by eliknebel** [comment] 2023-06-20 18:17
Duplicate of #3700

**Closed by eliknebel** 2023-06-20 18:17 UTC
